FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Use the development command
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 