services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # ports:
    #   - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/app/backend
      - ./predictor:/app/predictor
      - backend_models:/app/backend/app/models/trained
      - ./backend/.env:/app/backend/.env
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_CORS_ORIGINS=["http://localhost:80","http://frontend:3000","http://nginx:80"]
      - DATABASE_URL=postgresql://smartshelf:smartshelf_password@db:5432/smartshelf_db
      - DEBUG=false
      - SECRET_KEY=${SECRET_KEY:-production-secret-key}
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=smartshelf
      - POSTGRES_PASSWORD=smartshelf_password
      - POSTGRES_DB=smartshelf_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartshelf -d smartshelf_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  backend_models:
    driver: local
  postgres_data:
    driver: local 